config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users
    ActiveAdmin.routes(self)
    root to: "pages#home"
    #projects
    resources :project_requests
    #landings
    get 'travel' => 'pages#travel', as: :travel
    get 'rhythm' => 'pages#rhythm_and_soul', as: :'rhythm'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project_request.rb
class ProjectRequest < ApplicationRecord
  validates_presence_of :name, presence: true
  validates_presence_of :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      new_user_session_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :travel, :rhythm_and_soul ]

  def home
  end

  def faq
  end

  def about
  end

  # Landing pages
  def travel
    render 'pages/landings/travel/landing_travel'
  end

  def rhythm_and_soul
    render 'pages/landings/rhythm/landing_rhythm'
  end
end

app/controllers/project_requests_controller.rb
class ProjectRequestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create ]
  before_action :set_project, only: [:edit]

  include ProjectRequestsHelper

  def new
    @new_project = ProjectRequest.new
  end

  def create
    @new_project = ProjectRequest.new project_requests_params

    set_new_project_instance

    respond_to do |format|
      if @new_project.save
        format.html { redirect_to root_path }
        format.js
        flash[:notice] = t('controllers.projects.success')
        AdminNotificationMailer.new_project_notification(@new_project).deliver
      else
        format.html { render 'edit' }
        format.js
        flash[:alert] = t('controllers.projects.fail')
      end
    end
  end

  def edit
  end

  private

  def project_requests_params
    params.require(:project_request).permit(:name,
                                             :email,
                                             :description,
                                             :travel,
                                             :home)
  end

  def set_project
    @project = ProjectRequest.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_wrapper_page_style
    wrap = ""
    if travel
      wrap = "main-wrapper-travel"
    elsif rhythm
      wrap = "main-wrapper-rhythm"
    else
      wrap = ""
    end
    wrap
  end

  def nav_wrapper
    wrap = ""
    if travel
      wrap = "nav-wrapper-travel"
    elsif rhythm
      wrap = "nav-wrapper-rhythm"
    else
      wrap = "nav-wrapper-rocket"
    end
    wrap
  end

  def is_path?(paths)
    request.path.include?(paths)
  end

  def rocket
    is_path?("/")
  end

  def rhythm
    is_path?("/rhythm")
  end

  def travel
    is_path?("/travel")
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/project_requests_helper.rb
module ProjectRequestsHelper
  def budget_range
    ranges = ["2,000€ - 3,000€",
             "3,000€ - 4,000€",
             " > 4000€"]
    ranges.each { |range| range }
  end

  def link_to_new_project(wording, style)
    link_to "#{wording}", new_project_request_path(@new_project),
                                      class: "#{style} openSliderBtn",
                                      remote: true
  end

  def url_ancestor(url_fragment)
    request.referer.include? url_fragment
  end

  def conditional_proj_req_submit
    form_wrap = ""
    if url_ancestor 'travel'
      form_wrap = "travel_simple_form_wrap"
    elsif url_ancestor 'rhythm'
      form_wrap = "rhy_simple_form_wrap"
    else
      form_wrap = "rocket_simple_form_wrap"
    end
    form_wrap
  end

  def set_new_project_instance
    project = @new_project
    if url_ancestor 'travel'
      project.travel = true
    elsif url_ancestor 'rhythm'
      project.rhythm = true
    else
      project.home = true
    end
    project.save
  end

  def project_form_title
    if url_ancestor 'en/rhythm'
      I18n.locale = "en"
      I18n.t('rhythm.modal_contact_title')
    elsif url_ancestor '/rhythm'
      I18n.locale = "fr"
      I18n.t('rhythm.modal_contact_title')
    elsif url_ancestor 'en'
      I18n.locale = "en"
      I18n.t('modal_contact_title')
    else
      I18n.locale = "fr"
      I18n.t('modal_contact_title')
    end
  end

  def project_form_text
    if request.referer.include? 'en/rhythm'
      I18n.locale = "en"
      ('<p class="project_form_text">' + I18n.t("rhythm.project_form_text") + '</p>').html_safe
    elsif url_ancestor 'fr/rhythm'
      I18n.locale = "fr"
      ('<p class="project_form_text">' + I18n.t("rhythm.project_form_text") + '</p>').html_safe
    elsif url_ancestor '/rhythm'
      I18n.locale = "fr"
      ('<p class="project_form_text">' + I18n.t("rhythm.project_form_text") + '</p>').html_safe
    else
      ""
    end
  end

  def project_text_area_placeholder
    if url_ancestor 'en/rhythm'
      I18n.locale = "en"
      I18n.t('simple_form.proj_req.rhythm_text_area')
    elsif url_ancestor '/rhythm'
      I18n.locale = I18n.default_locale
      I18n.t('simple_form.proj_req.rhythm_text_area')
    elsif url_ancestor 'fr/rhythm'
      I18n.locale = I18n.default_locale
      I18n.t('simple_form.proj_req.rhythm_text_area')
    elsif url_ancestor 'en'
      I18n.locale = "en"
      I18n.t('simple_form.proj_req.rocket_text_area')
    else
      I18n.locale = "fr"
      I18n.t('simple_form.proj_req.rocket_text_area')
    end
  end
end

app/views/layouts/_footer.html.slim
.footer-content
  span= "© 2017 rocketmvp. All right reserved"
  = link_to_new_project("Contact", "")

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"]
    = stylesheet_link_tag    'application', media: 'all'
    = action_cable_meta_tag
    = csrf_meta_tags
    title
      = meta_title
    |  <meta name="description" content="
    = meta_description
    | ">
    |  <meta property="og:title" content="
    = meta_title
    | " />
    meta[property="og:type" content="website"]
    |  <meta property="og:url" content="
    = request.original_url
    | " /> <meta property="og:image" content="
    = image_url(meta_image)
    | " /> <meta property="og:description" content="
    = meta_description
    | " /> <meta property="og:site_name" content="
    = meta_title
    | " />
    meta[name="twitter:card" content="summary_large_image"]
    |  <meta name="twitter:site" content="
    = DEFAULT_META['twitter_account']
    | "> <meta name="twitter:title" content="
    = meta_title
    | "> <meta name="twitter:description" content="
    = meta_description
    | "> <meta name="twitter:creator" content="
    = DEFAULT_META['twitter_account']
    | "> <meta name="twitter:image:src" content="
    = image_url(meta_image)
    | ">
    |  <meta itemprop="name" content="
    = meta_title
    | "> <meta itemprop="description" content="
    = meta_description
    | "> <meta itemprop="image" content="
    = image_url(meta_image)
    | ">
  body class="#{main_wrapper_page_style}"
    script[src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"]
    #wrapper-nav.wrap-pad class="#{nav_wrapper}"
      - if content_for?(:navbar)
        = yield(:navbar)
      - else
        = render 'shared/navbar'
    = render 'shared/flashes'

    #main-wrapper
      #contactSliderwrapper
        #contactSliderContainer
        #closeSliderBtn
        #slider-bg-overlay
      = yield


      #modal-window.modal.fade[role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]

    = javascript_include_tag 'application'

    .footer-container.clearfix
      - if content_for?(:footer)
        = yield(:footer)
      - else
        = render 'layouts/footer'

    - if content_for?(:analytics)
      = yield(:analytics)
    - else
      = render "shared/analytics"

app/views/layouts/application.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"]
    = stylesheet_link_tag    'application', media: 'all'
    = action_cable_meta_tag
    = csrf_meta_tags
    title
      = meta_title
    |  <meta name="description" content="
    = meta_description
    | ">
    |  <meta property="og:title" content="
    = meta_title
    | " />
    meta[property="og:type" content="website"]
    |  <meta property="og:url" content="
    = request.original_url
    | " /> <meta property="og:image" content="
    = image_url(meta_image)
    | " /> <meta property="og:description" content="
    = meta_description
    | " /> <meta property="og:site_name" content="
    = meta_title
    | " />
    meta[name="twitter:card" content="summary_large_image"]
    |  <meta name="twitter:site" content="
    = DEFAULT_META['twitter_account']
    | "> <meta name="twitter:title" content="
    = meta_title
    | "> <meta name="twitter:description" content="
    = meta_description
    | "> <meta name="twitter:creator" content="
    = DEFAULT_META['twitter_account']
    | "> <meta name="twitter:image:src" content="
    = image_url(meta_image)
    | ">
    |  <meta itemprop="name" content="
    = meta_title
    | "> <meta itemprop="description" content="
    = meta_description
    | "> <meta itemprop="image" content="
    = image_url(meta_image)
    | ">
  body
    script[src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"]
    #wrapper-nav.wrap-pad
      - if content_for?(:navbar)
        = yield(:navbar)
      - else
        = render 'shared/navbar'
    = render 'shared/flashes'

    #main-wrapper
      - if content_for?(:body)
        = yield(:body)

      #modal-window.modal.fade[role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]

    = javascript_include_tag 'application'

    .footer-container.clearfix
      - if content_for?(:footer)
        = yield(:footer)
      - else
        = render 'layouts/footer'

    - if content_for?(:analytics)
      = yield(:analytics)
    - else
      = render "shared/analytics"

app/views/pages/_contact.html.slim
.contact-content
    h3= t('home.contact_title')
    p= t('home.contact_content')

    .cta
      - cta = t('general.get_in_touch')
      = link_to_new_project(cta, "contact-btn")

app/views/pages/_faq_banner.html.slim
#wrapper-faq-banner

app/views/pages/_get_started.html.slim
.left-panel
  h1= t('home.get_s_title')
  h5= t('home.get_s_subtitle')

  .nav-on-gets
    #gets-box-1.active-val
      span
        = t('home.get_s_1_title')
    #gets-box-2
      span
        = t('home.get_s_2_title')
    #gets-box-3
      span
        = t('home.get_s_3_title')
    #gets-box-4
      span
        = t('home.get_s_4_title')
    #gets-box-5
      span
        = t('home.get_s_5_title')

.right-panel
  .gets-box-1.gets-box
    p= t('home.get_s_1_content')

  .gets-box-2.gets-box.hidden
    p= t('home.get_s_2_content')

  .gets-box-3.gets-box.hidden
    p= t('home.get_s_3_content')

  .gets-box-4.gets-box.hidden
    p= t('home.get_s_4_content')

  .gets-box-5.gets-box.hidden
    p= t('home.get_s_5_content')

app/views/pages/_home_banner.html.slim
#wrapper-banner
  = video_tag("/videos/banner-intro.mp4", autoplay: :autoplay, loop: :loop)

  .banner-cta
    h1= t('.banner_intro')
    h5= t('.banner_prop')

    - cta = t('general.get_in_touch')
    = link_to_new_project(cta, "grow desktop-show")

    = link_to t('.sumbit_project'), new_project_request_path(@new_project), class: ' openSliderBtn mobile-show'

  .arrow-down
    .arrow-container
      a.arrow href="#wrapper-body"

app/views/pages/_mission.html.slim
.mission-content.clearfix
  .left-col
    h1= t('home.mission_title')
    h5= t('home.mission_subtitle')

    #mission2.mission-box
      .banner.banner-1
        = image_tag 'technologies.svg'
      .text
        p= t('home.mission_content_2')

  .right-col
    #mission1.mission-box
      .banner.banner-2
        = image_tag 'code.svg'
      .text
        p= t('home.mission_content_1')

    #mission3.mission-box
      .banner.banner-3
        = image_tag 'startup.svg'
      .text
        p= t('home.mission_content_3')

app/views/pages/_mission.slim
h1= t('home.mission_title')

app/views/pages/_offer.html.slim
.offer-title
  h1= t('home.offer_title')
  h5= t('home.offer_subtitle')

.packages-container
  #pack1.package.pack-1.grow
    .title
      h2= t('home.pack_1_title')
      h5= t('home.pack_1_price')
    .sub-title
      h4= t('home.pack_1_sub')
    .description
      p= t('home.pack_1_desc')
    .items
      span= t('home.pack_1_i_1')
      span= t('home.pack_1_i_2')
      span= t('home.pack_1_i_3')
      span= t('home.pack_1_i_4')
      span= t('home.pack_2_i_1')
      span= t('home.pack_2_i_2')
    .cta
      span
        - cta = t('home.pack_1_cta')
        = link_to_new_project(cta, "basic-offer-btn")

  #pack2.package.pack-2.grow
    .title
      h2= t('home.pack_2_title')
      h5= t('home.pack_2_price')
    .sub-title
      h4= t('home.pack_2_sub')
    .description
      p= t('home.pack_2_desc')
    .items
      span= t('home.pack_1_i_1')
      span= t('home.pack_1_i_2')
      span= t('home.pack_1_i_3')
      span= t('home.pack_1_i_4')
      span= t('home.pack_2_i_1')
      span= t('home.pack_2_i_2')
    .cta
      span
      - cta = t('home.pack_2_cta')
      = link_to_new_project(cta, "premium-offer-btn")

app/views/pages/_value.html.slim
.val-title
  h1= t('home.value_title')
  h5= t('home.value_subtitle')

.panel-values.clearfix
  .val-row-1
    .val-box-1.options
      .content
        h5 class=('entr')
          = t('home.val_1_title')
        p= t('home.val_1_content')

    .val-box-2.options
      .content
        h5 class=('buz')
          = t('home.val_2_title')
        p= t('home.val_2_content')

  .val-row-2
    .val-box-3.options
      .content
        h5 class=('anal')
          = t('home.val_3_title')
        p= t('home.val_3_content')

    .val-box-4.options
      .content
        h5 class=('conf')
          = t('home.val_4_title')
        p= t('home.val_4_content')

app/views/pages/faq.html.slim
= render 'faq_banner'

#wrapper-body.wrap-pad
  h1= 'Pricing'
  p= 'Do you charge by the hour / flat rate?'
  p= 'Is there a fee for maintenance and hosting?'

  h1= 'Product'
  p= 'Can I ask for iterations?'
  p= 'Which technology are you using?'
  p= 'How long does it take to get to a first verison?'
  p= 'Once finished, how do I access the source code?'

  h1= 'Design'
  p= 'Do you provide Ux design?'
  p= 'Can I brought my design / interface?'

  h1= 'Business'
  p= 'Do you provide digital marketing guidance once my product is ready to go?'

app/views/pages/home.html.slim
= render 'home_banner'

#wrapper-body.clearfix

  .mission-container.clearfix
    = render 'mission'

  .value-container.clearfix
    = render 'value'

  .process-container.clearfix
    = render 'get_started'

  .offer-container.clearfix
    = render 'offer'

  .contact-container.clearfix
    = render 'contact'

app/views/pages/landings/rhythm/_banner.html.slim
#wrapper-banner.banner-rhythm
  .wrap-items
    .intro
      h1 = t('rhythm.banner.cta')
      span = raw t('rhythm.banner.exp')
      .rhy-banner
        = image_tag 'rhythm-banner-rocket.svg'
    .action
      - cta = t('rhythm.banner.get_in_touch')
      = link_to_new_project(cta, "rhy-banner-btn desktop-show")

      = link_to t('.sumbit_project'), new_project_request_path(@new_project), class: 'openSliderBtn mobile-show'

app/views/pages/landings/rhythm/_footer.html.slim
.footer-content.rhy-footer
  span= "© 2017 Rhythm & Soul. All right reserved"
  = link_to_new_project("Contact", "")

app/views/pages/landings/rhythm/_navbar.html.slim
nav#nav-main
  .left-side
    = link_to rhythm_path, class: "logo" do
      = image_tag "rhythm-logo.svg"

  .right-side
    - cta = t('rhythm.navbar.get_in_touch')
    = link_to_new_project(cta, "grow desktop-show")

    - if I18n.locale == I18n.default_locale
      = link_to "English", { :locale=>'en' }
    - else
      = link_to "Français", { :locale=>'fr' }

  .slider

#nav-trigger
  i.fa.fa-bars

nav#nav-mobile

app/views/pages/landings/rhythm/_value_prop.html.slim
h3= t('rhythm.props-title')

.props-wrap

  .prop1.prop-box
    .prop-top
      = image_tag '003-spotify.svg'
    .prop-bot
      h4= t('rhythm.prop1-title')
      p= t('rhythm.prop1').html_safe

  .prop2.prop-box
    .prop-top
      = image_tag '002-calendar.svg'
    .prop-bot
      h4= t('rhythm.prop2-title')
      p= t('rhythm.prop2').html_safe

  .prop3.prop-box
    .prop-top
      =image_tag '001-tickets.svg'
    .prop-bot
      h4= t('rhythm.prop3-title')
      p= t('rhythm.prop3').html_safe

app/views/pages/landings/rhythm/landing_rhythm.html.slim
- content_for :navbar do
  = render 'pages/landings/rhythm/navbar'

= render 'pages/landings/rhythm/banner'

#wrapper-body.clearfix

  .rhy-value-prop-container
    = render 'pages/landings/rhythm/value_prop'

- content_for :footer do
  = render 'pages/landings/rhythm/footer'

app/views/pages/landings/travel/_banner.html.slim
#wrapper-banner.banner-travel-bg
  .intro
    h1 = t('travel.banner.cta')
    h5 = t('travel.banner.exp')
  .action
    - cta = t('travel.banner.get_in_touch')
    = link_to_new_project(cta, "grow desktop-show")

app/views/pages/landings/travel/_footer.html.slim
.footer-content
  span= "© 2017 experiencia. All right reserved"
  = link_to_new_project("Contact", "")

app/views/pages/landings/travel/_navbar.html.slim
nav#nav-main.travel-nav
  .left-side
    = link_to travel_path, class: "logo" do
      = image_tag "experiencia-logo-rocketmvp.svg"

  .right-side
    = link_to t('.our_service'), root_path
    - cta = t('general.get_in_touch')
    = link_to_new_project(cta, "grow desktop-show")

    - if I18n.locale == I18n.default_locale
      = link_to "English", { :locale=>'en' }
    - else
      = link_to "Français", { :locale=>'fr' }

  .slider

#nav-trigger
  i.fa.fa-bars

nav#nav-mobile

app/views/pages/landings/travel/_travel_navbar.html.slim
nav#nav-main
  .left-side
    = link_to root_path, class: "logo" do
      = image_tag "rocket-mvp-logo.svg"

  .right-side
    = link_to t('.our_service'), root_path
    = link_to t('.sumbit_project'), new_project_request_path(@new_project), class: 'mobile-show'

  .slider

#nav-trigger
  i.fa.fa-bars

nav#nav-mobile

app/views/pages/landings/travel/_travel_navbar.slim
nav#nav-main
  .left-side
    = link_to root_path, class: "logo" do
      = image_tag "rocket-mvp-logo.svg"

  .right-side
    = link_to t('.our_service'), root_path
    = link_to t('.sumbit_project'), new_project_request_path(@new_project), class: 'mobile-show'

  .slider

#nav-trigger
  i.fa.fa-bars

nav#nav-mobile

app/views/pages/landings/travel/_value_prop.html.slim
p= "blabla"

app/views/pages/landings/travel/_value_prop.slim
p= "blabla"

app/views/pages/landings/travel/landing_travel.html.slim
- content_for :navbar do
  = render 'pages/landings/travel/navbar'

= render 'pages/landings/travel/banner'

#wrapper-body.clearfix
  = render 'pages/landings/travel/value_prop'

- content_for :footer do
  = render 'pages/landings/travel/footer'

app/views/pages/landings/travel/landing_travel.slim
- content_for :navbar do
  = render 'pages/landings/travel/travel_navbar'

- content_for :body do
  = render 'pages/landings/travel/banner'

  #wrapper-body.clearfix
    = render 'pages/landings/travel/value_prop'

app/views/project_requests/_new_project.html.erb
<div class="wrapper-proj-req-erb <%= conditional_proj_req_submit %>">
  <span class="slider-intro"><%= project_form_title %></span>
  <%= project_form_text %>
  <%= render 'projects_form', new_project: @new_project %>
  <div class="powered-wrapper">
    <%= link_to root_path do %>
      <%= image_tag 'rocket.svg' %>
      <span class="powered"><%= t('home.slider.powered_by') %></span>
    <% end %>
  </div>
</div>

app/views/project_requests/_projects_form.html.slim
= simple_form_for new_project, html: { class: 'proj_req_form' }  do |f|

  = f.text_field :name,
                 placeholder: I18n.t('simple_form.proj_req.your_last_name'),
                 required: true,
                 class: 'name-form'

  = f.text_field :email,
                 placeholder: I18n.t('simple_form.proj_req.your_email'),
                 required: true,
                 class: 'email-form'

  = f.text_area :description,
                placeholder: project_text_area_placeholder,
                class: 'text-form'

  = f.button :submit, I18n.t('simple_form.proj_req.project_submit')

app/views/project_requests/new.html.slim
#wrapper-project-form
  h1= t('.new_proj_title')
  = render 'projects_form'

app/views/project_requests/new.js.erb
$("#contactSliderContainer").html("<%= j render 'new_project', new_project: @new_project %>");

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-101110801-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-tokeep.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.slim
nav#nav-main
  .left-side
    = link_to root_path, class: "logo" do
      = image_tag "rocket-mvp-logo.svg"

  .right-side
    = link_to t('.our_service'), root_path
    = link_to t('.sumbit_project'), new_project_request_path(@new_project), class: 'mobile-show'
    / = link_to t('.qa'), faq_path
    / = link_to t('.about'), about_path

    - if I18n.locale == I18n.default_locale
      = link_to "English", { :locale=>'en' }
    - else
      = link_to "Français", { :locale=>'fr' }

    - if user_signed_in?
      = link_to "Admin Sign Out", destroy_user_session_path, method: :delete
  .slider

#nav-trigger
  i.fa.fa-bars

nav#nav-mobile